O1 <- read.table("~/Career/TC/Courses/Core Methods in EDM/clustering/online-tutor.csv", sep = ",", header = TRUE)
O2 <- kmeans(O1, 5)
aggregate(O1,by=list(O2$cluster),FUN=mean)
O3 <- data.frame(O1, O2$cluster)
install.packages("cluster")
library(cluster)
clusplot(O3, O2$cluster, labels=5, color = TRUE)
O4 <- dplyr::select(O1, height, glasses)
O5 <- kmeans(O4, 5)
aggregate(O4,by=list(O5$cluster),FUN=mean)
O6 <- data.frame(O4, O5$cluster)
clusplot(O6, O5$cluster, labels=5, color = TRUE)